In [ ]:
list=[1,2.3,"pp"]
print(list)

[1, 2.3, 'pp']


In [ ]:
a=int(input())
b=int(input())
s=a+b
print(s)

1
2
3


In [ ]:
#creating a 1-D array
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(arr[1])
arr[2]=90
print(arr)

[1 2 3]
2
[ 1  2 90]


In [ ]:
arr2=np.array([[2,3,4],[7,8,9]])
print(arr2)
print(arr2[0][2])

[[2 3 4]
 [7 8 9]]
4


In [ ]:
arr3=np.array(["hi","im"])
print(arr3)

['hi' 'i']


In [ ]:
#arange helps in spacing values in equal intervals
arr4=np.arange(10,20,2)
print(arr4)

[10 12 14 16 18]


In [ ]:
#displaying random values between 0 and 1
arr5=np.random.rand(5)
print(arr5)
arr6=np.random.randint(4,10)
print(arr6)

[0.70786751 0.77664581 0.54062131 0.16636904 0.57528505]
7


In [ ]:
a=[2,3,4]
print(np.repeat(a,3))

[2 2 2 3 3 3 4 4 4]


In [ ]:
a=[2,3,4]
print(np.tile(a,3))

[2 3 4 2 3 4 2 3 4]


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import pandas as pd
path="/content/drive/MyDrive/dataset/cars.csv"
data=pd.read_csv(path)
print(data.head(5))

          Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
